name: CI/CD Pipeline for Dockerized App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/purrfect-timing:latest .
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/purrfect-timing:latest

      # Deploy to VM
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker pull ghcr.io/${{ secrets.DOCKER_USERNAME }}/purrfect-timing:latest
            docker stop purrfect-timing || true
            docker rm purrfect-timing || true
            docker run -d --name purrfect-timing -p 3000:3000 --restart unless-stopped ghcr.io/${{ secrets.DOCKER_USERNAME }}/purrfect-timing:latest
