name: Test SSH Connection

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log into the VM
      - name: Test SSH Connection to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            echo "Successfully logged into the VM!"
          debug: true
